projects:
  arclickcubes20190308204937:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AR Click Cubes/API/ARClickCubesAPI.swift
        docsFilePath: graphql
        graphQLApiId: sbfpfnxcvrbdrihmevl7nzfhm4
      endpoints:
        prod: >-
          https://nyeiz2h4 bzchbkg6qpes7ivoga.appsync-api.us-east-1.amazonaws.com/graphql
