projects:
  arclickcubes20190308204937:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AR Click Cubes/API/ARClickCubesAPI.swift
        docsFilePath: graphql
        graphQLApiId: azfdv4yuzfdnbi4urp5qj2z6iy
      endpoints:
        prod: >-
          https://mp5yutegijeolmauedhe467edq.appsync-api.us-east-1.amazonaws.com/graphql
