projects:
  ARClickCubes20190308173004:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AR Click Cubes/API/ARClickCubesAPI.swift
        docsFilePath: graphql
        graphQLApiId: b6xxan3t3jfz5ce67horvtabqy
      endpoints:
        prod: >-
          https://gnnhsumpbzce5ewzwyqnw7bp4m.appsync-api.us-east-1.amazonaws.com/graphql
