projects:
  arclickcubes20190308204937:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AR Click Cubes/API/ARClickCubesAPI.swift
        docsFilePath: graphql
        graphQLApiId: 7vfg5ut25fcavmw2fikad2hxzm
      endpoints:
        prod: >-
          https://sncajiwr3vhvdgae7pix7stzxq.appsync-api.us-east-1.amazonaws.com/graphql
