projects:
  arclickcubes20190308204937:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AR Click Cubes/API/ARClickCubesAPI.swift
        docsFilePath: graphql
        graphQLApiId: g6yvmgewpbgonc2iraj5fxyksu
      endpoints:
        prod: >-
          https://brrx3t54tbb5jhheq67lfm4xdq.appsync-api.us-east-1.amazonaws.com/graphql
