projects:
  arclickcubes20190308204937:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AR Click Cubes/API/ARClickCubesAPI.swift
        docsFilePath: graphql
        graphQLApiId: zhngm3xhjvanvk3j2uapw7yowq
      endpoints:
        prod: >-
          https://3d47yijqrvd7pefa5af54aw5xa.appsync-api.us-east-1.amazonaws.com/graphql
