projects:
  arclickcubesapi:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: AR Click Cubes/API/ARClickCubesAPI.swift
        docsFilePath: graphql
        graphQLApiId: nc6cwv72q5au3aws5wutdr2ujy
      endpoints:
        prod: >-
          https://kzsppaynend2phethi7kkhjzxe.appsync-api.us-east-1.amazonaws.com/graphql
