# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.0'

target 'AR Click Cubes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AR Click Cubes
  pod 'AWSAppSync', ' ~> 2.9.0'
  pod 'AWSMobileClient', '~> 2.8.0'      # Required dependency
  pod 'AWSAuthUI', '~> 2.8.0'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.8.0'   # Optional dependency required to use drop-in UI

  pod 'SSZipArchive'

  target 'AR Click CubesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AR Click CubesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
