# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.118.1"

fastlane_require 'dotenv'

before_all do
    Dotenv.overload '.env.secret'
end

default_platform :ios

platform :ios do

    lane :incrementBuildNumber do
        # Automatically increments the last part of the build number.
        increment_build_number_in_plist(scheme: "#{ENV['APP_SCHEME']}")
    end

    lane :incrementVersion do
        increment_version_number_in_plist(scheme: "#{ENV['APP_SCHEME']}") # Automatically increment patch version number.
    end

    lane :testEnvVars do
        puts "the scheme #{ENV['APP_SCHEME']}"
        puts "the id #{ENV['APP_IDENTIFIER']}"
        puts "#{ENV['APP_SCHEME']}"
        # Loaded from .env (by fastlane)
        # puts "STUFF: #{ENV['STUFF']}"

        # Loaded from .env.secret (by us in before_all)
        # puts "SOME_API_TOKEN: #{ENV['SOME_API_TOKEN']}"

        # Loaded from .env.(<env>) where <env> is passed in from `fastlane test --env <env>` (by fastlane)
        # Ex: `fastlane test --env config` loads .env.config1
        # puts "CONFIG: #{ENV['CONFIG']}"
    end

    lane :release do
        match(
            git_url: "https://www.github.com/nickarthur/certificates.git",
            type: "appstore",
            app_identifier: "#{ENV['APP_IDENTIFIER']}",
            force: true,
            readonly: false)
        # sync_code_signing
        # disable_automatic_code_signing(path: "#{ENV['APP_NAME']}.xcodeproj")
        ensure_git_status_clean
        increment_build_number_in_plist(scheme: "#{ENV['APP_SCHEME']}",
        build_number: "1") # reset build number to 1 for a new release
        increment_version_number_in_plist(scheme: "#{ENV['APP_SCHEME']}") # Automatically increment patch version number.
        commit_version_bump
        add_git_tag
        build_app(scheme: "#{ENV['APP_SCHEME']}")
        # enable_automatic_code_signing(path: "#{ENV['APP_NAME']}.xcodeproj")

        upload_to_testflight(
            beta_app_feedback_email: "nickarthur.night.002@gmail.com",
            beta_app_description: "Click Screen to place cubes",
            demo_account_required: true,
            notify_external_testers: true,
            changelog: "This is my changelog of things that have changed in a log",
            beta_app_review_info: {
                contact_email: "lnickers@gmail.com",
                contact_first_name: "Lawrence",
                contact_last_name: "Nickerson",
                contact_phone: "15129610259}",
                demo_account_name: "testuser",
                demo_account_password: "test1234",
                notes: "this is review note for the reviewer <3 thank you for reviewing"
            },
            localized_app_info: {
                "default": {
                    feedback_email: "nickarthur.night.002@gmail.com",
                    marketing_url: "https://example.com/marketing-defafult",
                    privacy_policy_url: "https://termsfeed.com/privacy-policy/c665768f9f70bebf917094f5dfca94f8",
                    description: "Default description",
                }
            },
            localized_build_info: {
                "default": {
                    whats_new: "Default changelog",
                }
            }
        )

    end

    lane :screenshots do
        capture_screenshots
        frame_screenshots(white: true)
        upload_to_app_store
    end

    lane :frame do
        frame_screenshots(white: true)
        upload_to_app_store
    end

    lane :tests do
        run_tests(scheme: "#{ENV['APP_SCHEME']}")
    end

    lane :uploadNewBetaBuild do
        ensure_git_status_clean
       increment_build_number_in_plist(scheme: "#{ENV['APP_SCHEME']}") # Automatically increments the last part of the build number.
        commit_version_bump
        add_git_tag
        build_app(scheme: "#{ENV['APP_SCHEME']}")
        upload_to_testflight(changelog: "updated build...")
    end

    lane :betabits do
        ensure_git_status_clean
        increment_build_number_in_plist(scheme: "#{ENV['APP_SCHEME']}") # Automatically increments the last part of the build number.
        commit_version_bump
        add_git_tag
        build_app(scheme: "#{ENV['APP_SCHEME']}",
        workspace: "#{ENV['APP_NAME']}.xcworkspace",
        include_bitcode: true)
        upload_to_testflight(changelog: "another build...")
    end


    #desc "Creating a code signing certificate and provisioning profile"
    #lane :provision do
    #    produce(
    #        app_name: "#{ENV['APP_NAME']}",
    #        language: 'English',
    #        app_version: '1.0',
    #        sku: "#{ENV['APP_IDENTIFIER']}"
    #    )
    #    cert
    #    sigh(force: true)
    #end

    lane :screenshot do
        capture_screenshots
        frame_screenshots(white: true)
        upload_to_app_store
    end

    desc "Create ipa"
    lane :build do
        ensure_git_status_clean
        increment_version_number_in_plist # Automatically increment patch version number.
        commit_version_bump
        add_git_tag
        gym
    end

    desc "Upload to App Store and submit for review"
    lane :upload do
        deliver(
            submit_for_review: true
        )
    end

    desc "Provision, take screenshots, build and upload to App Store"
    lane :do_everything do
        provision
        screenshot
        build
        upload
    end

    error do |lane, exception|
    # This block is called if there was an error running a lane.
    end

end

